@startmindmap "end_points"
* api/v1
  ** /areas
    ***[#LightGreen] GET, GET/{id}
        ****[#LightBlue] ADMIN, OPERATOR
    ***[#LightGreen] POST, DELETE, PUT
        ****[#LightBlue] ADMIN
  ** /professionals
    ***[#LightGreen] GET, GET/{id}, POST, PUT, DELETE?
        ****[#LightBlue] ADMIN, OPERATOR
  ** /service-types
      ***[#LightGreen] GET, GET/{id}, POST, PUT, DELETE?
        ****[#LightBlue] ADMIN, OPERATOR
  ** /clients
      ***[#LightGreen] GET, GET/{id}, POST, PUT, DELETE?
        ****[#LightBlue] ADMIN, OPERATOR
@endmindmap