@startuml "Model"
    class Professional {
        name: String
        phone: String
        active: boolean
    }

    class Appointment {
        date: Date
        startTime: Time
        endTime: Time
        comments: String
        status: PRESENT | ABSENT | CANCEL | OPEN
    }

    class WorkScheduleItem {

    }

    class Area {

    }

    class Client {

    }

    class AppointmentType {

    }

    class User {

    }

@enduml